import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
await page.goto('http://refeitorio.picos.ifpi.edu.br/');
await page.getByText('☰').click();
await page.getByRole('link', { name: 'Login' }).click();
await page.getByRole('link', { name: 'Esqueci minha senha' }).click();
await page.locator('#id_matricula').click();
await page.locator('#id_matricula').fill('2011118tads0000');
await page.locator('#id_email').click();
await page.locator('#id_email').fill('2021118tads0000');
await page.locator('#id_senha').click();
await page.locator('#id_senha').fill('12345678');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').press('ArrowLeft');
await page.locator('#id_email').fill('capic.2021118tads0000');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').press('ArrowRight');
await page.locator('#id_email').fill('capic.2021118tads0000@aluno.ifpi.edu.br');
await page.getByRole('button', { name: ' Salvar' }).click();
await expect('Dados não conferem, procure o administrador!').toBeTruthy();
});